name: vg-infradesk
services:
  vg-infradesk:
    image: nginx:alpine
    container_name: vg-infradesk
    ports:
      - "9999:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
